# Generated by Django 4.0.4 on 2022-05-17 14:01

from django.db import migrations, models
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(default=0, max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
    ]
