# Generated by Django 4.0.4 on 2022-05-17 14:02

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='zip',
            field=localflavor.us.models.USZipCodeField(blank=True, default=0, max_length=10),
        ),
    ]
