# Generated by Django 4.0.4 on 2022-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_alter_guest_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.CharField(choices=[('standard', 'Standard'), ('soy-free', 'Soy-Free'), ('gluten-free', 'Gluten-Free')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
