# Generated by Django 4.0.4 on 2022-07-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_guest_meal_alter_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
    ]
